"""Update realisations ajout colonne link

Revision ID: 6cd2edcfbab2
Revises: fea55c801064
Create Date: 2026-03-18 18:12:12.869239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd2edcfbab2'
down_revision: Union[str, Sequence[str], None] = 'fea55c801064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realisations', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realisations', 'link')
    # ### end Alembic commands ###
